
name: Check markdown documents

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: lint-md-github-action
      # You may pin to the exact commit or the version.
      # uses: lint-md/github-action@c85852d6ed2623391ee4d027242d45c5c8afb86b
        uses: lint-md/github-action@v0.1.1
        with:
          # Lint-md configuration file path.
          configFile: .lintmdrc # optional, default is .lintmdrc
        # Whether you want to fail on warnings or not.
          failOnWarnings: false # optional, default is false
        # You can pass in multiple directories to be checked, separated by spaces.
          files: ./ # optional, default is ./
      
      - name: REUSE Compliance Check
      # You may pin to the exact commit or the version.
      # uses: fsfe/reuse-action@e7a435374d26d54b324fa6699d8eafb076340dfd
        uses: fsfe/reuse-action@v1.2.0
